import 'package:flutter/material.dart';

double borderRadius = 5.0;

const bgColor = Colors.blue;
const backgroundColor = Color.fromARGB(255, 7, 36, 18);
const palleteColor = Color.fromARGB(255, 11, 43, 15);
const titleTextColor = Colors.white;
const secondTitleText = Colors.white70;
const ColorHidup = Colors.blue;
const ColorMati = Colors.blue;
const AppBarColor = Color.fromARGB(255, 28, 49, 28);
const cardColor = Color.fromARGB(255, 15, 33, 15);
const cardTitleColor = Colors.white70;
const cardTextUnitColor = Colors.white;
const GridValueTextColor = Colors.white;
const CardLastChangeUpdateTextColor = Colors.white70;
const cardButtonColor = Color(0xff243D25);
const BackgroundCardButtonColor = Color.fromARGB(255, 24, 47, 25);
const graphPlotAreadColor = Color.fromARGB(255, 50, 92, 51);
const borderRadiusGlass = 5.0;
bool stateButtonPenyiramaan = false;
bool stateButtonPengisian = false;
bool stateButtonPhUp = false;
bool stateButtonPhDown = false;
bool stateButtonPpmUp = false;
//
const maxPh = 12;
const maxPpm = 1200;
const maxHumidity = 100;
const maxMoisture = 100;
const maxSchedulePpm = 7;
const maxSchedulePenyiraman = 9;
const maxPenyiraman = 300;
const maxIntervalOnPpm = 30000;
const maxIntervalOffPpm = 30000;
const maxIntervalOffPh = 30000;
const maxIntervalOnPh = 3000;
Color shadowColor = Colors.black;
double? height;
double? width;
double? cardWitdh;
double padding = 10;
String uid = '';
bool? SprayerButton;
Map<dynamic, dynamic> grafikData = {};
